name: matrix-exec
on: push

jobs:
  first-job:
    strategy:
      matrix:
        node-version : [18,19,20]
        operating-system: ['ubuntu-latest','windows-latest','mac-latest']
    
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: get-code
        uses: actions/checkout@v3
      
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      
      - name: Install Deps
        run: npm ci
      
      - name: Build project
        run: npm build
